server:
  port: 8080
spring:
    datasource:
        name: movierec
        url: jdbc:mariadb://47.99.205.186:3307/movierec
        username: root
        password: 1015sunqi
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.mariadb.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.movie.dal

#pagehelper分页插件
pagehelper:
    helperDialect: mariadb
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql